### ISSUE TITLE
VS sometimes errors out.

### ISSUE THREAD

**Issue by Ovyerus** [Ovyerus/knife-bot#13]
Noticed this happening on the Clara server earlier today, `vs` spewed out this odd message.
```
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:507:11)
    at ClientRequest.setHeader (_http_outgoing.js:511:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)
    at Object.request (https.js:233:15)
    at actualCall (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:129:33)
    at SequentialBucket.check (/home/moo/knife-bot/node_modules/eris/lib/util/SequentialBucket.js:70:28)
    at SequentialBucket.queue (/home/moo/knife-bot/node_modules/eris/lib/util/SequentialBucket.js:38:14)
    at Promise (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:281:40)
    at Promise._execute (/home/moo/knife-bot/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/moo/knife-bot/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/moo/knife-bot/node_modules/bluebird/js/release/promise.js:79:10)
    at RequestHandler.request (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:60:16)
    at Client.banGuildMember (/home/moo/knife-bot/node_modules/eris/lib/Client.js:1262:36)
    at Guild.banMember (/home/moo/knife-bot/node_modules/eris/lib/structures/Guild.js:445:49)
    at banMember (/home/moo/knife-bot/src/commands/vs/vs.js:39:33)
```

Never had this happened before and when I went to test this in my own server, it worked fine.

**Comment by sr229** [comment]
This is probably Eris IMHO, it has nothing to do with the bot core nor the command.

**Comment by Ovyerus** [comment]
Opened issue on official Eris repo.
abalabahaha/eris#276
